export { createPostgresGraphTranslator } from './runtime/create-postgres-graph-translator.js';
export { createPostgresSqlClient } from './runtime/create-postgres-sql-client.js';
export { initializeGraphSchema, startRecursiveClosurePostgresRuntime, waitForPostgres } from './runtime/recursive-closure-postgres-runtime.js';
export { applyDatalogFacts } from './execution/apply-datalog-facts.js';
export { executeTranslatedSql } from './execution/execute-translated-sql.js';
export { translateGraphOperation } from './translation/translate-graph-operation.js';
export type {
  DatalogConstantTerm,
  DatalogFact,
  DatalogFactPattern,
  DatalogTerm,
  DatalogVariableTerm,
  DeleteFactsOperation,
  EdgeFact,
  EdgeFactPattern,
  InsertFactsOperation,
  PostgresGraphOperation,
  SelectFactsOperation,
  SelectRecursiveClosureCountOperation,
  SelectEdgesOperation,
  SelectVertexByIdOperation,
  VertexFact,
  VertexFactPattern,
} from './contracts/postgres-graph-operation.js';
export { GraphTranslationError } from './contracts/graph-translation-error.js';
export type { GraphTranslationResult } from './contracts/graph-translation-result.js';
export type { PostgresGraphTarget } from './contracts/postgres-graph-target.js';
export type { PostgresGraphTranslator } from './contracts/postgres-graph-translator.js';
export type { PostgresSqlClient } from './runtime/create-postgres-sql-client.js';
export type { TranslatedSqlQuery } from './contracts/translated-sql-query.js';
export type {
  DatalogAtom,
  DatalogComparison,
  DatalogDirectiveStatement,
  DatalogFunctionCall,
  DatalogLiteral,
  DatalogNegatedAtom,
  DatalogProgram,
  DatalogQueryStatement,
  DatalogRuleStatement,
  DatalogScalarValue,
  DatalogSourceLocation,
  DatalogStatement,
  DatalogTypeName,
  DatalogWildcardTerm,
  NormalizedAtom,
  NormalizedFact,
  NormalizedFunctionCall,
  NormalizedLiteral,
  NormalizedProgram,
  NormalizedQuery,
  NormalizedRule,
  NormalizedVariable,
  PredicateSignature,
} from './contracts/datalog-program.js';
export type {
  BuiltinPredicateBinding,
  MemoryRelationBinding,
  PostgresTableBinding,
  PostgresViewBinding,
  PredicateBinding,
  PredicateCapabilities,
  PredicateCatalog,
  PredicateCatalogLookup,
  PredicateConstraint,
  PredicateIndex,
  PredicateStatistics,
  PredicateStorageBinding,
  RelationColumnBinding,
  WorkTableBinding,
} from './contracts/predicate-catalog.js';
export type {
  AggregateBinding,
  BooleanExpression,
  ColumnReference,
  ComparisonExpression,
  FunctionExpression,
  JoinCondition,
  LogicalAggregateNode,
  LogicalColumnId,
  LogicalDistinctNode,
  LogicalExpression,
  LogicalFilterNode,
  LogicalJoinNode,
  LogicalLimitNode,
  LogicalMaterializeNode,
  LogicalNodeId,
  LogicalPlan,
  LogicalPlanNode,
  LogicalProjectNode,
  LogicalScanNode,
  LogicalSortNode,
  LogicalUnionNode,
  LogicalValuesNode,
  LogicalWorkRelationScanNode,
  OutputColumn,
  ParameterReference,
  PlanDiagnostic,
  PlanParameter,
  PlanParameterId,
  ProjectionBinding,
  ScalarLiteral,
  SharedSubplan,
  SortKey,
} from './contracts/logical-plan.js';
export type {
  RecursiveDeduplication,
  RecursiveDeltaExpansion,
  RecursiveFixpoint,
  RecursiveRulePlan,
  RecursiveScc,
  RecursiveTermination,
  TransitiveClosureFastPath,
  WorkRelationDefinition,
} from './contracts/recursive-fixpoint.js';
export type {
  BackendKind,
  MemoryBuildIndexStep,
  MemoryEmitResultStep,
  MemoryIterativeFixpointStep,
  MemoryLoadRelationStep,
  MemoryPhysicalPlan,
  PhysicalPlan,
  PhysicalStepId,
  PostgresAnalyzeWorkRelationStep,
  PostgresCreateWorkRelationStep,
  PostgresEmitResultStep,
  PostgresExecuteStatementStep,
  PostgresIterativeFixpointStep,
  PostgresPhysicalPlan,
  PreparedStatementTemplate,
  SqlParameterValue,
} from './contracts/physical-plan.js';
export type {
  CompilerArtifacts,
  DatalogCompiler,
  DatalogCompilerOptions,
} from './contracts/compiler-pipeline.js';
